const $=s=>document.querySelector(s),KEY='fit-profile-v1';let data=JSON.parse(localStorage.getItem(KEY)||'null');function calc(d){const bmr=10*d.weight+6.25*d.height-5*d.age+(d.sex==='male'?5:-161),tdee=bmr*d.activity,mult=d.goal==='lose'?.82:d.goal==='gain'?1.1:1,cal=Math.round(tdee*mult),protein=Math.round(d.weight*(d.goal==='lose'?2:1.8)),fat=Math.round(d.weight*.8),carbs=Math.max(0,Math.round((cal-protein*4-fat*9)/4));return{cal,protein,fat,carbs}}function render(){if(!data)return;const m=calc(data);$('#weight').textContent=data.weight.toFixed(1);$('#fat').textContent=data.fat?data.fat.toFixed(1):'—';$('#calories').textContent=m.cal.toLocaleString('es-PE');$('#protein').innerHTML=m.protein+'<small> g</small>';$('#carbs').innerHTML=m.carbs+'<small> g</small>';$('#fats').innerHTML=m.fat+'<small> g</small>';$('#weightState').textContent=data.goal==='lose'?'Objetivo: pérdida de grasa':data.goal==='gain'?'Objetivo: ganancia muscular':'Objetivo: mantenimiento';$('#setup h2').textContent='Perfil configurado';$('#setup p').textContent='Tus recomendaciones están calculadas con tus datos actuales. Puedes actualizarlos cuando quieras.';$('#openProfile').innerHTML='Editar <b>→</b>';if(data.fat)document.querySelector('.fatRing').style.background='conic-gradient(var(--lime) 0 '+Math.min(100,data.fat)+'%,#1b2529 '+Math.min(100,data.fat)+'% 100%)'}function fill(){if(!data)return;$('#pWeight').value=data.weight;$('#pFat').value=data.fat||'';$('#pHeight').value=data.height;$('#pAge').value=data.age;$('#pSex').value=data.sex;$('#pActivity').value=data.activity;$('#pGoal').value=data.goal}$('#openProfile').onclick=()=>{fill();$('#profile').showModal()};$('.avatar').onclick=()=>{fill();$('#profile').showModal()};$('#profileForm').onsubmit=e=>{if(e.submitter?.value==='cancel')return;data={weight:+$('#pWeight').value,fat:+$('#pFat').value||null,height:+$('#pHeight').value,age:+$('#pAge').value,sex:$('#pSex').value,activity:+$('#pActivity').value,goal:$('#pGoal').value};localStorage.setItem(KEY,JSON.stringify(data));render()};render();
let settingActivity=data?.activity||1.55,settingGoal=data?.goal||'lose';
function syncSettings(){if(data){$('#sWeight').value=data.weight;$('#sFat').value=data.fat||'';$('#sHeight').value=data.height;$('#sAge').value=data.age;$('#sSex').value=data.sex;settingActivity=data.activity;settingGoal=data.goal}document.querySelectorAll('#mobility button').forEach(b=>b.classList.toggle('selected',+b.dataset.value===+settingActivity));document.querySelectorAll('#goalSwitch button').forEach(b=>b.classList.toggle('selected',b.dataset.goal===settingGoal));preview()}
function preview(){const d={weight:+$('#sWeight').value,height:+$('#sHeight').value,age:+$('#sAge').value,sex:$('#sSex').value,activity:+settingActivity,goal:settingGoal};if(!d.weight||!d.height||!d.age){$('#previewCalories').textContent='— kcal';$('#previewMacros').textContent='Completa tus datos para calcularlo.';return}const m=calc(d);$('#previewCalories').textContent=m.cal.toLocaleString('es-PE')+' kcal';$('#previewMacros').textContent='Proteína '+m.protein+'g · Carbos '+m.carbs+'g · Grasas '+m.fat+'g'}
document.querySelectorAll('nav [data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===b.dataset.view));if(b.dataset.view==='settingsView')syncSettings();scrollTo(0,0)});
document.querySelectorAll('#mobility button').forEach(b=>b.onclick=()=>{settingActivity=+b.dataset.value;document.querySelectorAll('#mobility button').forEach(x=>x.classList.toggle('selected',x===b));preview()});
document.querySelectorAll('#goalSwitch button').forEach(b=>b.onclick=()=>{settingGoal=b.dataset.goal;document.querySelectorAll('#goalSwitch button').forEach(x=>x.classList.toggle('selected',x===b));preview()});
['sWeight','sHeight','sAge','sSex','sFat'].forEach(id=>$('#'+id).addEventListener('input',preview));
$('#settingsForm').onsubmit=e=>{e.preventDefault();data={weight:+$('#sWeight').value,fat:+$('#sFat').value||null,height:+$('#sHeight').value,age:+$('#sAge').value,sex:$('#sSex').value,activity:+settingActivity,goal:settingGoal};localStorage.setItem(KEY,JSON.stringify(data));render();document.querySelector('nav [data-view="homeView"]').click()};
