const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],KEY='fit-profile-v1';
let data;try{data=JSON.parse(localStorage.getItem(KEY)||'null')}catch{data=null}
let settingActivity=data?.activity||1.55,settingGoal=data?.goal||'lose',settingDays=data?.trainingDays||3,settingPriority=data?.priority||'balanced',settingLevel=data?.level||'beginner',settingPlace=data?.place||'gym',settingEquipment=data?.equipment||['machines','barbell','dumbbells'],settingDuration=data?.duration||60,settingFocus=data?.trainingFocus||'hypertrophy';
function calc(d){const bmr=10*d.weight+6.25*d.height-5*d.age+(d.sex==='male'?5:-161),tdee=bmr*d.activity,mult=d.goal==='lose'?.82:d.goal==='gain'?1.1:1,cal=Math.round(tdee*mult),protein=Math.round(d.weight*(d.goal==='lose'?2:1.8)),fat=Math.round(d.weight*.8),carbs=Math.max(0,Math.round((cal-protein*4-fat*9)/4));return{cal,protein,fat,carbs}}
function render(){if(!data)return;const m=calc(data);$('#weight').textContent=data.weight.toFixed(1);$('#fat').textContent=data.fat?data.fat.toFixed(1):'—';$('#calories').textContent=m.cal.toLocaleString('es-PE');$('#protein').innerHTML=m.protein+'<small> g</small>';$('#carbs').innerHTML=m.carbs+'<small> g</small>';$('#fats').innerHTML=m.fat+'<small> g</small>';$('#weightState').textContent=data.goal==='lose'?'Objetivo: pérdida de grasa':data.goal==='gain'?'Objetivo: ganancia muscular':'Objetivo: mantenimiento';$('#setup h2').textContent='Perfil configurado';$('#setup p').textContent='Tus recomendaciones están calculadas con tus datos actuales.';$('#openProfile').innerHTML='Editar <b>→</b>';$('.fatRing').style.background=data.fat?'conic-gradient(var(--lime) 0 '+Math.min(100,data.fat)+'%,#1b2529 '+Math.min(100,data.fat)+'% 100%)':'conic-gradient(#1b2529 0 100%)'}
function preview(){const d={weight:+$('#sWeight').value,height:+$('#sHeight').value,age:+$('#sAge').value,sex:$('#sSex').value,activity:+settingActivity,goal:settingGoal};if(!d.weight||!d.height||!d.age){$('#previewCalories').textContent='— kcal';$('#previewMacros').textContent='Completa tus datos para calcularlo.';return}const m=calc(d);$('#previewCalories').textContent=m.cal.toLocaleString('es-PE')+' kcal';$('#previewMacros').textContent='Proteína '+m.protein+'g · Carbos '+m.carbs+'g · Grasas '+m.fat+'g'}
function syncSettings(){if(data){$('#sWeight').value=data.weight;$('#sFat').value=data.fat||'';$('#sHeight').value=data.height;$('#sAge').value=data.age;$('#sSex').value=data.sex;settingActivity=data.activity;settingGoal=data.goal;settingDays=data.trainingDays||3;settingPriority=data.priority||'balanced';settingLevel=data.level||'beginner';settingPlace=data.place||'gym';settingEquipment=data.equipment||['machines','barbell','dumbbells'];settingDuration=data.duration||60}document.querySelectorAll('#prioritySwitch button').forEach(b=>b.classList.toggle('selected',b.dataset.priority===settingPriority));document.querySelectorAll('#levelSwitch button').forEach(b=>b.classList.toggle('selected',b.dataset.level===settingLevel));document.querySelectorAll('#placeSwitch button').forEach(b=>b.classList.toggle('selected',b.dataset.place===settingPlace));document.querySelectorAll('#equipmentSwitch button').forEach(b=>b.classList.toggle('selected',settingEquipment.includes(b.dataset.equipment)));document.querySelectorAll('#durationSwitch button').forEach(b=>b.classList.toggle('selected',+b.dataset.duration===+settingDuration));document.querySelectorAll('#mobility button').forEach(b=>b.classList.toggle('selected',+b.dataset.value===+settingActivity));document.querySelectorAll('#trainingFocus button').forEach(b=>b.classList.toggle('selected',b.dataset.focus===settingFocus));document.querySelectorAll('#goalSwitch button').forEach(b=>b.classList.toggle('selected',b.dataset.goal===settingGoal));document.querySelectorAll('#trainingDays button').forEach(b=>b.classList.toggle('selected',+b.dataset.days===+settingDays));preview()}
function go(view){$('.view').forEach(v=>v.classList.toggle('active',v.id===view));$('nav [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='settingsView')syncSettings();if(view==='trainingView')renderTraining();if(view==='progressView')renderProgress();if(view==='nutritionView')renderNutrition();window.scrollTo(0,0)}
$('nav [data-view]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.view)));
$('#openProfile').addEventListener('click',()=>go('settingsView'));$('.avatar').addEventListener('click',()=>go('settingsView'));
document.querySelectorAll('#mobility button').forEach(b=>b.addEventListener('click',()=>{settingActivity=+b.dataset.value;document.querySelectorAll('#mobility button').forEach(x=>x.classList.toggle('selected',x===b));preview()}));
document.querySelectorAll('#prioritySwitch button').forEach(b=>b.addEventListener('click',()=>{settingPriority=b.dataset.priority;document.querySelectorAll('#prioritySwitch button').forEach(x=>x.classList.toggle('selected',x===b));preview()}));
document.querySelectorAll('#levelSwitch button').forEach(b=>b.addEventListener('click',()=>{settingLevel=b.dataset.level;document.querySelectorAll('#levelSwitch button').forEach(x=>x.classList.toggle('selected',x===b))}));
document.querySelectorAll('#placeSwitch button').forEach(b=>b.addEventListener('click',()=>{settingPlace=b.dataset.place;document.querySelectorAll('#placeSwitch button').forEach(x=>x.classList.toggle('selected',x===b));if(settingPlace==='home'&&settingEquipment.includes('machines')){settingEquipment=settingEquipment.filter(x=>x!=='machines');document.querySelector('[data-equipment="machines"]').classList.remove('selected')}}));
document.querySelectorAll('#equipmentSwitch button').forEach(b=>b.addEventListener('click',()=>{const e=b.dataset.equipment;if(settingEquipment.includes(e)){if(settingEquipment.length>1)settingEquipment=settingEquipment.filter(x=>x!==e)}else settingEquipment.push(e);document.querySelectorAll('#equipmentSwitch button').forEach(x=>x.classList.toggle('selected',settingEquipment.includes(x.dataset.equipment)))}));
document.querySelectorAll('#durationSwitch button').forEach(b=>b.addEventListener('click',()=>{settingDuration=+b.dataset.duration;document.querySelectorAll('#durationSwitch button').forEach(x=>x.classList.toggle('selected',x===b))}));
document.querySelectorAll('#trainingFocus button').forEach(b=>b.addEventListener('click',()=>{settingFocus=b.dataset.focus;document.querySelectorAll('#trainingFocus button').forEach(x=>x.classList.toggle('selected',x===b))}));
document.querySelectorAll('#goalSwitch button').forEach(b=>b.addEventListener('click',()=>{settingGoal=b.dataset.goal;document.querySelectorAll('#goalSwitch button').forEach(x=>x.classList.toggle('selected',x===b));preview()}));
document.querySelectorAll('#trainingDays button').forEach(b=>b.addEventListener('click',()=>{settingDays=+b.dataset.days;document.querySelectorAll('#trainingDays button').forEach(x=>x.classList.toggle('selected',x===b))}));
['sWeight','sHeight','sAge','sSex','sFat'].forEach(id=>$('#'+id).addEventListener('input',preview));
$('#settingsForm').addEventListener('submit',e=>{e.preventDefault();data={weight:+$('#sWeight').value,fat:+$('#sFat').value||null,height:+$('#sHeight').value,age:+$('#sAge').value,sex:$('#sSex').value,activity:+settingActivity,goal:settingGoal,trainingDays:+settingDays,priority:settingPriority,level:settingLevel,place:settingPlace,equipment:settingEquipment,duration:+settingDuration,trainingFocus:settingFocus};localStorage.setItem(KEY,JSON.stringify(data));render();go('homeView')});
const exerciseDB={
full:[['Sentadilla','Piernas','3 × 6–10'],['Press banca','Pecho','3 × 6–10'],['Remo','Espalda','3 × 8–12'],['Peso muerto rumano','Femoral','3 × 8–12'],['Press militar','Hombros','2 × 8–12'],['Curl + tríceps','Brazos','2 × 10–15']],
upper:[['Press banca','Pecho','3 × 6–10'],['Remo','Espalda','3 × 8–12'],['Press militar','Hombros','3 × 8–12'],['Jalón al pecho','Espalda','3 × 8–12'],['Elevaciones laterales','Hombros','2 × 12–15'],['Curl bíceps','Bíceps','2 × 10–15'],['Extensión tríceps','Tríceps','2 × 10–15']],
lower:[['Sentadilla','Cuádriceps','3 × 6–10'],['Peso muerto rumano','Femoral','3 × 8–12'],['Prensa','Piernas','3 × 10–12'],['Hip thrust','Glúteos','3 × 8–12'],['Gemelos','Pantorrilla','3 × 12–15'],['Plancha','Core','3 × 30–60s']],
push:[['Press banca','Pecho','3 × 6–10'],['Press inclinado','Pecho','3 × 8–12'],['Press militar','Hombros','3 × 8–12'],['Elevaciones laterales','Hombros','3 × 12–15'],['Extensión tríceps','Tríceps','3 × 10–15']],
pull:[['Jalón al pecho','Espalda','3 × 8–12'],['Remo','Espalda','3 × 8–12'],['Peso muerto rumano','Cadena posterior','3 × 6–10'],['Face pull','Hombro posterior','3 × 12–15'],['Curl bíceps','Bíceps','3 × 10–15']],
legs:[['Sentadilla','Cuádriceps','3 × 6–10'],['Prensa','Piernas','3 × 10–12'],['Peso muerto rumano','Femoral','3 × 8–12'],['Hip thrust','Glúteos','3 × 8–12'],['Curl femoral','Femoral','2 × 10–15'],['Gemelos','Pantorrilla','3 × 12–15']]
};
function splitFor(days){
const plans={
2:{name:'Full Body A/B',week:[['Lunes','Full Body A','full'],['Martes','Descanso'],['Miércoles','Descanso'],['Jueves','Full Body B','full'],['Viernes','Descanso'],['Sábado','Descanso'],['Domingo','Descanso']]},
3:{name:'Full Body 3 días',week:[['Lunes','Full Body A','full'],['Martes','Descanso'],['Miércoles','Full Body B','full'],['Jueves','Descanso'],['Viernes','Full Body C','full'],['Sábado','Descanso'],['Domingo','Descanso']]},
4:{name:'Upper / Lower',week:[['Lunes','Upper A','upper'],['Martes','Lower A','lower'],['Miércoles','Descanso'],['Jueves','Upper B','upper'],['Viernes','Lower B','lower'],['Sábado','Descanso'],['Domingo','Descanso']]},
5:{name:'Upper / Lower + PPL',week:[['Lunes','Upper','upper'],['Martes','Lower','lower'],['Miércoles','Descanso'],['Jueves','Push','push'],['Viernes','Pull','pull'],['Sábado','Legs','legs'],['Domingo','Descanso']]},
6:{name:'Push / Pull / Legs',week:[['Lunes','Push A','push'],['Martes','Pull A','pull'],['Miércoles','Legs A','legs'],['Jueves','Descanso'],['Viernes','Push B','push'],['Sábado','Pull B','pull'],['Domingo','Legs B','legs']]}
};return plans[days]||plans[3]}
function applyFocusPrescription(list){return list.map(e=>[e[0],e[1],displayPrescription(e)])}
function equipmentForExercise(name){const n=name.toLowerCase();if(n.includes('flexion')||n.includes('plancha')||n.includes('zancada'))return 'Peso corporal';if(n.includes('banda'))return 'Bandas';if(n.includes('mancuerna')||n.includes('goblet'))return 'Mancuernas';if(n.includes('prensa')||n.includes('jalón')||n.includes('curl femoral')||n.includes('extensión tríceps'))return 'Máquina';if(n.includes('press banca')||n.includes('press inclinado')||n.includes('sentadilla')||n.includes('peso muerto')||n.includes('hip thrust')||n.includes('remo'))return settingEquipment.includes('barbell')?'Barra':settingEquipment.includes('dumbbells')?'Mancuernas':'Peso corporal';if(n.includes('curl bíceps')||n.includes('curl +')||n.includes('elevaciones')||n.includes('press militar'))return settingEquipment.includes('dumbbells')?'Mancuernas':settingEquipment.includes('bands')?'Bandas':'Barra';if(n.includes('face pull'))return settingEquipment.includes('bands')?'Bandas':'Polea';if(n.includes('gemelos'))return settingPlace==='gym'?'Máquina':'Peso corporal';return settingPlace==='gym'?'Máquina':'Peso corporal'}
function displayPrescription(e){const r=repRangeForExercise(e[0]);if(e[0].toLowerCase().includes('plancha'))return e[2];const sets=(e[2].match(/^\d+/)||['3'])[0];return sets+' × '+r[0]+'–'+r[1]}
function prioritizedExercises(type){
let base=exerciseDB[type]||exerciseDB.full;base=base.map(e=>{let name=e[0];if(settingPlace==='home'){if(name==='Prensa')name=settingEquipment.includes('dumbbells')?'Sentadilla goblet':'Zancadas';if(name==='Jalón al pecho')name=settingEquipment.includes('bands')?'Jalón con banda':'Remo invertido';if(name==='Press banca'&&!settingEquipment.includes('barbell'))name=settingEquipment.includes('dumbbells')?'Press con mancuernas':'Flexiones';if(name==='Press inclinado'&&!settingEquipment.includes('dumbbells'))name='Flexiones con pies elevados'}return[name,e[1],e[2]]});if(!data||data.priority==='balanced'||!data.priority)return base;
const targets={glutes:['Glúteos','Piernas','Cuádriceps','Femoral','Pantorrilla'],chest:['Pecho','Bíceps','Tríceps','Brazos'],back:['Espalda','Hombros','Hombro posterior']}[data.priority]||[];
return base.map(e=>{let sets=e[2];if(settingLevel==='beginner')sets=sets.replace(/^4 ×/,'3 ×').replace(/^3 ×/,'2 ×');if(settingLevel==='advanced'&&targets.includes(e[1]))sets=sets.replace(/^2 ×/,'3 ×').replace(/^3 ×/,'4 ×');else if(settingLevel!=='beginner'&&targets.includes(e[1]))sets=sets.replace(/^2 ×/,'3 ×').replace(/^3 ×/,'4 ×');return[e[0],e[1],sets]})
}
function renderTraining(){const box=$('#trainingPlan');if(!box)return;if(!data?.trainingDays){$('#splitName').textContent='Tu plan de entrenamiento';$('#splitIntro').textContent='Indica en Configuración cuántos días puedes entrenar.';box.innerHTML='<div class="emptyTraining"><b>Aún no hay un split</b>Configura tus días disponibles para generar tu plan.</div>';return}const split=splitFor(+data.trainingDays),label={balanced:'desarrollo equilibrado',glutes:'énfasis en glúteos y piernas',chest:'énfasis en pecho y brazos',back:'énfasis en espalda y hombros'}[data.priority||'balanced'];$('#splitName').textContent=split.name;$('#splitIntro').textContent='Semana con '+data.trainingDays+' sesiones · '+label+' · descansos incluidos.';box.innerHTML='<div class="splitSummary"><span><b>'+data.trainingDays+'</b> entrenos / semana</span><span><b>'+(7-data.trainingDays)+'</b> días de descanso</span></div>'+split.week.map(d=>{if(!d[2])return '<article class="workoutDay restDay"><div class="dayTop"><div><span>'+d[0].toUpperCase()+'</span><h3>Descanso</h3></div><span>RECUPERACIÓN</span></div><div class="exercise"><i>☾</i><div><b>Recupera y prepárate</b><small>Sueño, hidratación y actividad ligera</small></div><span>Sin pesas</span></div></article>';let ex=prioritizedExercises(d[2]);const maxEx=settingDuration<=30?4:settingDuration<=45?5:settingDuration<=60?6:8;ex=ex.slice(0,maxEx);return '<article class="workoutDay"><div class="dayTop"><div><span>'+d[0].toUpperCase()+'</span><h3>'+d[1]+'</h3></div><span>'+ex.length+' ejercicios</span></div>'+ex.map((e,i)=>'<div class="exercise"><i>'+(i+1)+'</i><div><b>'+e[0]+' <em class="exerciseEquipment">('+equipmentForExercise(e[0])+')</em></b><small>'+e[1]+'</small></div><span>'+e[2]+'</span></div>').join('')+'<button type="button" class="startWorkoutBtn" data-start-workout data-name="'+d[1]+'" data-type="'+d[2]+'">INICIAR ENTRENAMIENTO</button></article>'}).join('')}
render();
renderTraining();
const WORKOUT_KEY='fit-workouts-v1';
let activeWorkout=null,workoutInterval=null,restInterval=null,restSeconds=0;
function workoutHistory(){try{return JSON.parse(localStorage.getItem(WORKOUT_KEY)||'[]')}catch{return[]}}
function lastExercisePerformance(name){for(const w of workoutHistory()){const e=w.exercises?.find(x=>x.name===name);if(e)return e}return null}
function startWorkout(dayName,type){
 const exercises=applyFocusPrescription(prioritizedExercises(type)).slice(0,settingDuration<=30?4:settingDuration<=45?5:settingDuration<=60?6:8);
 activeWorkout={name:dayName,type,start:Date.now(),exercises:exercises.map(e=>({name:e[0],muscle:e[1],equipment:equipmentForExercise(e[0]),sets:Array.from({length:Math.max(2,parseInt(e[2])||3)},()=>({kg:'',reps:'',rir:'',done:false}))}))};
 renderActiveWorkout();go('workoutSessionView');clearInterval(workoutInterval);workoutInterval=setInterval(updateWorkoutTimer,1000);updateWorkoutTimer()
}
function updateWorkoutTimer(){if(!activeWorkout)return;const s=Math.floor((Date.now()-activeWorkout.start)/1000),m=Math.floor(s/60);$('#workoutTimer').textContent=String(m).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function renderActiveWorkout(){
 $('#activeWorkoutName').textContent=activeWorkout.name;
 $('#activeExercises').innerHTML=activeWorkout.exercises.map((e,ei)=>'<article class="activeExercise"><div class="activeExerciseHead"><div><h3>'+e.name+' <em class="exerciseEquipment">('+e.equipment+')</em></h3><span>'+e.muscle+'</span></div></div>'+previousPerformanceHTML(e.name)+progressionHTML(e.name)+'<div class="setLabels"><span>Serie</span><span>kg</span><span>Reps</span><span>RIR</span><span>✓</span></div>'+e.sets.map((s,si)=>'<div class="setRow" data-e="'+ei+'" data-s="'+si+'"><b>'+(si+1)+'</b><input inputmode="decimal" data-field="kg" value="'+s.kg+'" placeholder="0"><input inputmode="numeric" data-field="reps" value="'+s.reps+'" placeholder="0"><input inputmode="numeric" data-field="rir" value="'+s.rir+'" placeholder="2"><button type="button" class="setDone '+(s.done?'done':'')+'">'+(s.done?'✓':'○')+'</button></div>').join('')+'</article>').join('');
 document.querySelectorAll('.setRow input').forEach(i=>i.addEventListener('input',e=>{const r=e.target.closest('.setRow');activeWorkout.exercises[+r.dataset.e].sets[+r.dataset.s][e.target.dataset.field]=e.target.value;updateSessionSummary()}));
 document.querySelectorAll('.setDone').forEach(b=>b.addEventListener('click',()=>{const r=b.closest('.setRow'),s=activeWorkout.exercises[+r.dataset.e].sets[+r.dataset.s];s.done=!s.done;b.classList.toggle('done',s.done);b.textContent=s.done?'✓':'○';if(s.done)startRestTimer();updateSessionSummary()}));updateSessionSummary()
}

function repRangeForExercise(name){const n=name.toLowerCase(),iso=n.includes('elevaciones')||n.includes('curl')||n.includes('tríceps')||n.includes('gemelos')||n.includes('face pull'),compound=n.includes('press banca')||n.includes('sentadilla')||n.includes('peso muerto')||n.includes('remo');if(n.includes('plancha'))return[30,60];if(settingFocus==='strength')return iso?[8,12]:compound?[3,6]:[5,8];if(settingFocus==='mixed')return iso?[10,15]:compound?[5,8]:[8,12];return iso?[10,15]:compound?[6,10]:[8,12]}
function exercisePR(name){let best=null;workoutHistory().forEach(w=>(w.exercises||[]).filter(e=>e.name===name).forEach(e=>(e.sets||[]).filter(s=>s.done&&+s.kg>0&&+s.reps>0).forEach(s=>{const kg=+s.kg,reps=+s.reps,e1=kg*(1+reps/30);if(!best||e1>best.e1)best={kg,reps,e1,date:w.start}})));return best}
function exerciseProgression(name){const prev=lastExercisePerformance(name),range=repRangeForExercise(name);if(!prev)return{label:'BASE',text:'Registra tu primera sesión para calcular la progresión.'};const done=(prev.sets||[]).filter(s=>s.done&&+s.reps>0);if(!done.length)return{label:'REPETIR',text:'No hay series completas anteriores. Usa una carga cómoda y registra todas las series.'};const weighted=done.filter(s=>+s.kg>0);if(!weighted.length)return{label:'REPS',text:'Intenta mejorar al menos 1 repetición manteniendo buena técnica.'};const minReps=Math.min(...weighted.map(s=>+s.reps)),maxKg=Math.max(...weighted.map(s=>+s.kg));if(minReps>=range[1]){const inc=maxKg<20?1:maxKg<60?2.5:5;return{label:'SUBIR PESO',text:'Completaste el rango. Prueba '+(maxKg+inc)+' kg y vuelve al rango bajo ('+range[0]+'–'+(range[0]+2)+' reps).'}}if(minReps>=range[0])return{label:'MÁS REPS',text:'Mantén '+maxKg+' kg e intenta sumar 1 repetición por serie hasta llegar a '+range[1]+'.'};return{label:'MANTENER',text:'Mantén '+maxKg+' kg hasta lograr al menos '+range[0]+' reps por serie.'}}
function progressionHTML(name){const p=exerciseProgression(name),pr=exercisePR(name);return '<div class="progressionTip"><span>'+p.label+'</span><p>'+p.text+'</p>'+(pr?'<small>🏆 PR: '+pr.kg+' kg × '+pr.reps+' · e1RM '+Math.round(pr.e1)+' kg</small>':'')+'</div>'}
function previousPerformanceHTML(name){const p=lastExercisePerformance(name);if(!p)return '<div class="previousPerformance">Primera sesión registrada</div>';const sets=p.sets.filter(s=>s.done&&(+s.reps||0)).map(s=>(s.kg||0)+' kg × '+s.reps).join(' · ');return '<div class="previousPerformance"><b>Anterior:</b> '+(sets||'Sin series completadas')+'</div>'}
function startRestTimer(){clearInterval(restInterval);restSeconds=90;showRest();restInterval=setInterval(()=>{restSeconds--;showRest();if(restSeconds<=0){clearInterval(restInterval);const el=$('#restTimer');if(el)el.classList.add('finished')}},1000)}
function showRest(){let el=$('#restTimer');if(!el){el=document.createElement('div');el.id='restTimer';el.className='restTimer';document.body.appendChild(el)}el.classList.remove('finished');el.innerHTML='<span>DESCANSO</span><b>'+Math.floor(restSeconds/60)+':'+String(restSeconds%60).padStart(2,'0')+'</b><div><button type="button" data-rest="-30">−30s</button><button type="button" data-rest="30">+30s</button><button type="button" data-rest="skip">Omitir</button></div>';el.classList.add('show')}
document.addEventListener('click',e=>{const b=e.target.closest('[data-rest]');if(!b)return;if(b.dataset.rest==='skip'){clearInterval(restInterval);$('#restTimer')?.classList.remove('show');return}restSeconds=Math.max(0,restSeconds+(+b.dataset.rest));showRest()});
function updateSessionSummary(){if(!activeWorkout)return;let sets=0,volume=0;activeWorkout.exercises.forEach(e=>e.sets.forEach(s=>{if(s.done){sets++;volume+=(+s.kg||0)*(+s.reps||0)}}));$('#sessionSummary').innerHTML='<span><b>'+sets+'</b> series</span><span><b>'+Math.round(volume).toLocaleString('es-PE')+'</b> kg volumen</span>'}
function finishActiveWorkout(){if(!activeWorkout)return;activeWorkout.end=Date.now();activeWorkout.exercises.forEach(e=>{const old=exercisePR(e.name);e.sets.forEach(s=>{if(s.done&&+s.kg>0&&+s.reps>0){const e1=(+s.kg)*(1+(+s.reps)/30);if(!old||e1>old.e1)s.pr=true}})});const history=workoutHistory();history.unshift(activeWorkout);localStorage.setItem(WORKOUT_KEY,JSON.stringify(history.slice(0,100)));clearInterval(workoutInterval);clearInterval(restInterval);$('#restTimer')?.classList.remove('show');activeWorkout=null;renderWorkoutHistory();go('trainingView')}
document.addEventListener('click',e=>{const b=e.target.closest('[data-start-workout]');if(b)startWorkout(b.dataset.name,b.dataset.type)});
$('#closeWorkout').addEventListener('click',()=>{if(activeWorkout)go('trainingView')});
$('#finishWorkout').addEventListener('click',finishActiveWorkout);

function workoutStats(w){let sets=0,volume=0,best=null;w.exercises?.forEach(e=>e.sets?.forEach(s=>{if(s.done){sets++;const v=(+s.kg||0)*(+s.reps||0);volume+=v;if(+s.kg>0&&(!best||+s.kg>best.kg))best={name:e.name,kg:+s.kg,reps:+s.reps||0}}}));return{sets,volume:Math.round(volume),best}}
function formatWorkoutDate(ts){return new Intl.DateTimeFormat('es-PE',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(ts))}
function renderWorkoutHistory(){const list=$('#historyList'),stats=$('#historyStats');if(!list||!stats)return;const hist=workoutHistory();if(!hist.length){stats.innerHTML='';list.innerHTML='<div class="emptyTraining"><b>Aún no hay entrenamientos</b>Finaliza tu primera sesión y aparecerá aquí.</div>';return}let totalVol=0,totalSets=0;hist.forEach(w=>{const s=workoutStats(w);totalVol+=s.volume;totalSets+=s.sets});stats.innerHTML='<div><b>'+hist.length+'</b><span>Sesiones</span></div><div><b>'+totalSets+'</b><span>Series</span></div><div><b>'+totalVol.toLocaleString('es-PE')+'</b><span>kg volumen</span></div>';list.innerHTML=hist.map((w,wi)=>{const s=workoutStats(w),mins=Math.max(1,Math.round(((w.end||w.start)-w.start)/60000));return '<article class="historyCard"><button type="button" class="historyToggle" data-history="'+wi+'"><div><span>'+formatWorkoutDate(w.start)+'</span><h3>'+w.name+'</h3></div><strong>'+mins+' min</strong></button><div class="historyMeta"><span>'+s.sets+' series</span><span>'+s.volume.toLocaleString('es-PE')+' kg volumen</span>'+(s.best?'<span>🏆 '+s.best.kg+' kg</span>':'')+'</div><div class="historyDetail" id="history-'+wi+'">'+(w.exercises||[]).map(e=>'<div class="historyExercise"><b>'+e.name+' <em class="exerciseEquipment">('+(e.equipment||'')+')</em></b><small>'+e.muscle+'</small><p>'+e.sets.filter(x=>x.done).map((x,i)=>(i+1)+'. '+(+x.kg||0)+' kg × '+(+x.reps||0)+' · RIR '+(x.rir===''?'—':x.rir)+(x.pr?' 🏆 PR':'')).join('<br>')+'</p></div>').join('')+'</div></article>'}).join('');document.querySelectorAll('.historyToggle').forEach(b=>b.addEventListener('click',()=>$('#history-'+b.dataset.history).classList.toggle('open')))}
$('#openHistory').addEventListener('click',()=>{renderWorkoutHistory();go('workoutHistoryView')});
$('#closeHistory').addEventListener('click',()=>go('trainingView'));

const WEIGHT_KEY='fit-weight-log-v1';
function localDay(){const d=new Date(),off=d.getTimezoneOffset();return new Date(d.getTime()-off*60000).toISOString().slice(0,10)}
function normalizeWeightLog(raw){if(!Array.isArray(raw))return[];const byDay=new Map();raw.forEach(x=>{const day=String(x?.day||'').slice(0,10),weight=Number(x?.weight);if(/^\d{4}-\d{2}-\d{2}$/.test(day)&&Number.isFinite(weight)&&weight>=30&&weight<=300)byDay.set(day,{day,weight,time:Number(x?.time)||Date.now()})});return[...byDay.values()].sort((a,b)=>a.day.localeCompare(b.day)).slice(-365)}
function weightLog(){try{return normalizeWeightLog(JSON.parse(localStorage.getItem(WEIGHT_KEY)||'[]'))}catch{return[]}}
function saveWeightEntry(weight,day=localDay()){weight=Number(weight);day=String(day||localDay()).slice(0,10);if(!Number.isFinite(weight)||weight<30||weight>300||!/^\d{4}-\d{2}-\d{2}$/.test(day))return false;const log=weightLog(),found=log.find(x=>x.day===day);if(found){found.weight=weight;found.time=Date.now()}else log.push({day,weight,time:Date.now()});const clean=normalizeWeightLog(log);localStorage.setItem(WEIGHT_KEY,JSON.stringify(clean));if(data&&day===localDay()){data.weight=weight;localStorage.setItem(KEY,JSON.stringify(data));render()}renderProgress(true);return true}
function avgWeight(items){return items.length?items.reduce((a,x)=>a+Number(x.weight),0)/items.length:null}
function weightTrend(log){const pts=normalizeWeightLog(log).slice(-7);if(pts.length<2)return null;const first=pts[0],last=pts[pts.length-1],delta=last.weight-first.weight,days=Math.max(1,Math.round((Date.parse(last.day+'T12:00:00')-Date.parse(first.day+'T12:00:00'))/86400000));return{delta,days,count:pts.length}}
function renderProgress(force=false){const log=weightLog(),hist=workoutHistory(),date=$('#logWeightDate'),input=$('#logWeight');if(date&&!date.value)date.value=localDay();if(input&&data?.weight&&!input.value)input.value=Number(data.weight).toFixed(1);const recent=log.slice(-7),a=avgWeight(recent),trend=weightTrend(log),trendEl=$('#weightTrend');if(trendEl)trendEl.textContent=!trend?'Añade otro registro':(Math.abs(trend.delta)<.05?'Estable':(trend.delta>0?'+':'')+trend.delta.toFixed(1)+' kg')+' · '+trend.days+'d';const sessions30=hist.filter(w=>Date.now()-w.start<30*864e5),vol30=sessions30.reduce((n,w)=>n+workoutStats(w).volume,0),summary=$('#progressSummary');if(summary)summary.innerHTML='<div><span>PESO ACTUAL</span><b>'+(log.length?log.at(-1).weight.toFixed(1):data?.weight?.toFixed(1)||'—')+' <small>kg</small></b></div><div><span>ÚLTIMOS REGISTROS</span><b>'+(a!=null?a.toFixed(1):'—')+' <small>kg prom.</small></b></div><div><span>30 DÍAS</span><b>'+sessions30.length+' <small>sesiones</small></b></div><div><span>VOLUMEN 30D</span><b>'+Math.round(vol30).toLocaleString('es-PE')+' <small>kg</small></b></div>';renderWeightChart(log);renderWeekly(hist);renderPRs(hist)}
function renderWeightChart(raw){const el=$('#weightChart'),history=$('#weightHistory');if(!el||!history)return;const pts=normalizeWeightLog(raw).slice(-30);history.innerHTML=pts.slice().reverse().map(x=>'<button type="button" class="weightChip" data-day="'+x.day+'" data-weight="'+x.weight+'"><span>'+x.day.slice(5)+'</span><b>'+x.weight.toFixed(1)+' kg</b></button>').join('');if(pts.length<2){el.innerHTML='<div class="emptyProgress">Registra pesos en 2 fechas distintas para ver la tendencia.</div>';bindWeightChips();return}const values=pts.map(x=>x.weight),min=Math.min(...values),max=Math.max(...values),spread=Math.max(.4,max-min),yMin=min-spread*.2,yMax=max+spread*.2,w=320,h=150,left=34,right=10,top=12,bottom=24,plotW=w-left-right,plotH=h-top-bottom;const dates=pts.map(x=>Date.parse(x.day+'T12:00:00')),dMin=Math.min(...dates),dMax=Math.max(...dates),dRange=Math.max(86400000,dMax-dMin);const coords=pts.map((x,i)=>({x:left+(dates[i]-dMin)/dRange*plotW,y:top+(yMax-x.weight)/(yMax-yMin)*plotH,p:x}));const grid=[0,.5,1].map(t=>{const y=top+t*plotH,val=yMax-t*(yMax-yMin);return '<line x1="'+left+'" y1="'+y+'" x2="'+(w-right)+'" y2="'+y+'" class="chartGrid"/><text x="'+(left-5)+'" y="'+(y+3)+'" text-anchor="end" class="chartLabel">'+val.toFixed(1)+'</text>'}).join('');const path=coords.map((p,i)=>(i?'L':'M')+p.x.toFixed(1)+' '+p.y.toFixed(1)).join(' ');el.innerHTML='<svg viewBox="0 0 '+w+' '+h+'" role="img" aria-label="Tendencia de peso">'+grid+'<path d="'+path+'" class="weightLine"/>'+coords.map(p=>'<circle cx="'+p.x.toFixed(1)+'" cy="'+p.y.toFixed(1)+'" r="4" class="weightPoint"><title>'+p.p.day+': '+p.p.weight.toFixed(1)+' kg</title></circle>').join('')+'<text x="'+left+'" y="'+(h-4)+'" class="chartDate">'+pts[0].day.slice(5)+'</text><text x="'+(w-right)+'" y="'+(h-4)+'" text-anchor="end" class="chartDate">'+pts.at(-1).day.slice(5)+'</text></svg>';bindWeightChips()}
function bindWeightChips(){document.querySelectorAll('.weightChip').forEach(b=>b.addEventListener('click',()=>{if($('#logWeightDate'))$('#logWeightDate').value=b.dataset.day;if($('#logWeight'))$('#logWeight').value=Number(b.dataset.weight).toFixed(1)}))}
function renderWeekly(hist){const el=$('#weeklyTraining');let weeks=[];for(let i=3;i>=0;i--){const end=Date.now()-i*7*864e5,start=end-7*864e5,ws=hist.filter(x=>x.start>=start&&x.start<end),vol=ws.reduce((n,w)=>n+workoutStats(w).volume,0);weeks.push({n:ws.length,vol})}const max=Math.max(1,...weeks.map(x=>x.vol));el.innerHTML=weeks.map((x,i)=>'<div class="weekBar"><div><i style="height:'+Math.max(4,x.vol/max*100)+'%"></i></div><b>'+x.n+'</b><span>S'+(i+1)+'</span><small>'+Math.round(x.vol/1000*10)/10+'k kg</small></div>').join('')}
function renderPRs(hist){const names=new Set;hist.forEach(w=>(w.exercises||[]).forEach(e=>names.add(e.name)));const prs=[...names].map(name=>({name,pr:exercisePR(name)})).filter(x=>x.pr).sort((a,b)=>b.pr.e1-a.pr.e1).slice(0,8);$('#prList').innerHTML=prs.length?prs.map(x=>'<div><span>🏆</span><p><b>'+x.name+'</b><small>'+x.pr.kg+' kg × '+x.pr.reps+'</small></p><strong>'+Math.round(x.pr.e1)+'<small> e1RM</small></strong></div>').join(''):'<div class="emptyProgress">Tus PR aparecerán después de registrar entrenamientos.</div>'}
$('#weightLogForm').addEventListener('submit',e=>{e.preventDefault();const w=Number($('#logWeight').value),day=$('#logWeightDate').value||localDay();if(saveWeightEntry(w,day)){const btn=e.currentTarget.querySelector('button[type="submit"]');if(btn){const old=btn.textContent;btn.textContent='GUARDADO ✓';setTimeout(()=>btn.textContent=old,900)}}});

const FOOD_LIBRARY=[
{name:'Pechuga de pollo cocida',kcal:165,protein:31,carbs:0,fat:3.6,cat:'Proteínas'},
{name:'Huevo entero',kcal:143,protein:12.6,carbs:.7,fat:9.5,cat:'Proteínas'},
{name:'Atún en agua escurrido',kcal:116,protein:25.5,carbs:0,fat:.8,cat:'Proteínas'},
{name:'Carne de res magra cocida',kcal:217,protein:26,carbs:0,fat:12,cat:'Proteínas'},
{name:'Leche entera',kcal:61,protein:3.2,carbs:4.8,fat:3.3,cat:'Lácteos'},
{name:'Yogur griego natural',kcal:97,protein:9,carbs:3.9,fat:5,cat:'Lácteos'},
{name:'Arroz blanco cocido',kcal:130,protein:2.7,carbs:28.2,fat:.3,cat:'Carbohidratos'},
{name:'Papa sancochada',kcal:87,protein:1.9,carbs:20.1,fat:.1,cat:'Carbohidratos'},
{name:'Camote cocido',kcal:90,protein:2,carbs:20.7,fat:.2,cat:'Carbohidratos'},
{name:'Avena',kcal:389,protein:16.9,carbs:66.3,fat:6.9,cat:'Carbohidratos'},
{name:'Pan integral',kcal:247,protein:13,carbs:41,fat:4.2,cat:'Carbohidratos'},
{name:'Quinua cocida',kcal:120,protein:4.4,carbs:21.3,fat:1.9,cat:'Carbohidratos'},
{name:'Lentejas cocidas',kcal:116,protein:9,carbs:20.1,fat:.4,cat:'Legumbres'},
{name:'Frejoles cocidos',kcal:127,protein:8.7,carbs:22.8,fat:.5,cat:'Legumbres'},
{name:'Palta',kcal:160,protein:2,carbs:8.5,fat:14.7,cat:'Grasas'},
{name:'Maní',kcal:567,protein:25.8,carbs:16.1,fat:49.2,cat:'Grasas'},
{name:'Aceite de oliva',kcal:884,protein:0,carbs:0,fat:100,cat:'Grasas'},
{name:'Plátano',kcal:89,protein:1.1,carbs:22.8,fat:.3,cat:'Frutas'},
{name:'Manzana',kcal:52,protein:.3,carbs:13.8,fat:.2,cat:'Frutas'},
{name:'Mandarina',kcal:53,protein:.8,carbs:13.3,fat:.3,cat:'Frutas'}
];
const FAVORITES_KEY='fit-food-favorites-v1';
let favoriteOnly=false;
function favoriteFoods(){try{return JSON.parse(localStorage.getItem(FAVORITES_KEY)||'[]')}catch{return[]}}
function toggleFavorite(name){let f=favoriteFoods();f=f.includes(name)?f.filter(x=>x!==name):[...f,name];localStorage.setItem(FAVORITES_KEY,JSON.stringify(f));renderFoodSearch()}
function renderFoodSearch(){const box=$('#foodResults');if(!box)return;const q=($('#foodSearch')?.value||'').trim().toLowerCase(),favs=favoriteFoods();let foods=FOOD_LIBRARY.filter(x=>(!favoriteOnly||favs.includes(x.name))&&(!q||x.name.toLowerCase().includes(q)||x.cat.toLowerCase().includes(q))).slice(0,12);box.innerHTML=foods.length?foods.map((x,i)=>'<div class="libraryFood"><button type="button" class="favFood" data-fav="'+escapeFit(x.name)+'">'+(favs.includes(x.name)?'★':'☆')+'</button><button type="button" class="pickFood" data-pick="'+FOOD_LIBRARY.indexOf(x)+'"><div><b>'+x.name+'</b><span>'+x.cat+' · por 100 g</span></div><strong>'+x.kcal+' kcal</strong><small>P '+x.protein+' · C '+x.carbs+' · G '+x.fat+'</small></button></div>').join(''):'<div class="emptyProgress">No encontramos alimentos con esa búsqueda.</div>';$('[data-pick]').forEach(b=>b.addEventListener('click',()=>selectLibraryFood(+b.dataset.pick)));$('[data-fav]').forEach(b=>b.addEventListener('click',()=>toggleFavorite(b.dataset.fav)))}
function selectLibraryFood(i){const x=FOOD_LIBRARY[i];if(!x)return;$('#foodName').value=x.name;$('#foodKcal').value=x.kcal;$('#foodProtein').value=x.protein;$('#foodCarbs').value=x.carbs;$('#foodFat').value=x.fat;if(!$('#foodGrams').value)$('#foodGrams').value=100;$('#foodGrams').focus();$('#foodForm').scrollIntoView({behavior:'smooth',block:'center'})}
const NUTRITION_KEY='fit-nutrition-v1';
function nutritionData(){try{const x=JSON.parse(localStorage.getItem(NUTRITION_KEY)||'{}');return x&&typeof x==='object'?x:{}}catch{return{}}}
function dayFoods(day=localDay()){return nutritionData()[day]||[]}
function nutritionTotals(items){return items.reduce((a,x)=>{a.kcal+=+x.kcal||0;a.protein+=+x.protein||0;a.carbs+=+x.carbs||0;a.fat+=+x.fat||0;return a},{kcal:0,protein:0,carbs:0,fat:0})}
function macroProgress(label,value,target,unit){const pct=target?Math.min(100,value/target*100):0;return '<div class="macroProgress"><div><span>'+label+'</span><b>'+Math.round(value)+' / '+Math.round(target||0)+' '+unit+'</b></div><i><em style="width:'+pct+'%"></em></i></div>'}
function renderNutrition(){renderFoodSearch();const dash=$('#nutritionDashboard'),list=$('#mealList');if(!dash||!list)return;const foods=dayFoods(),t=nutritionTotals(foods),goal=data?calc(data):{cal:0,protein:0,carbs:0,fat:0},remain=Math.max(0,goal.cal-t.kcal);dash.innerHTML='<div class="nutritionHero"><div><span>CONSUMIDO</span><b>'+Math.round(t.kcal).toLocaleString('es-PE')+'</b><small>kcal</small></div><div class="remainingRing"><b>'+Math.round(remain).toLocaleString('es-PE')+'</b><span>kcal restantes</span></div></div>'+macroProgress('Proteína',t.protein,goal.protein,'g')+macroProgress('Carbohidratos',t.carbs,goal.carbs,'g')+macroProgress('Grasas',t.fat,goal.fat,'g');const meals=['Desayuno','Almuerzo','Cena','Snack'];list.innerHTML=meals.map(meal=>{const m=foods.filter(x=>x.meal===meal),mt=nutritionTotals(m);return '<article class="mealCard"><div class="mealHead"><div><span>'+meal.toUpperCase()+'</span><b>'+Math.round(mt.kcal)+' kcal</b></div><small>'+m.length+' alimento'+(m.length===1?'':'s')+'</small></div>'+(m.length?m.map(x=>'<div class="foodRow"><div><b>'+escapeFit(x.name)+'</b><span>'+Math.round(x.grams)+' g · P '+Math.round(x.protein)+' · C '+Math.round(x.carbs)+' · G '+Math.round(x.fat)+'</span></div><strong>'+Math.round(x.kcal)+' kcal</strong><button type="button" data-food="'+x.id+'" aria-label="Eliminar">×</button></div>').join(''):'<p class="emptyMeal">Sin alimentos registrados.</p>')+'</article>'}).join('');$('[data-food]').forEach(b=>b.addEventListener('click',()=>removeFood(b.dataset.food)))}
function escapeFit(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function addFood(){const grams=Number($('#foodGrams').value),factor=grams/100,base={kcal:Number($('#foodKcal').value),protein:Number($('#foodProtein').value),carbs:Number($('#foodCarbs').value),fat:Number($('#foodFat').value)};if(!$('#foodName').value.trim()||!Number.isFinite(grams)||grams<=0||Object.values(base).some(v=>!Number.isFinite(v)||v<0))return false;const db=nutritionData(),day=localDay(),arr=db[day]||[];arr.push({id:Date.now().toString(36)+Math.random().toString(36).slice(2,6),name:$('#foodName').value.trim(),grams,meal:$('#foodMeal').value,kcal:base.kcal*factor,protein:base.protein*factor,carbs:base.carbs*factor,fat:base.fat*factor});db[day]=arr;localStorage.setItem(NUTRITION_KEY,JSON.stringify(db));renderNutrition();return true}
function removeFood(id){const db=nutritionData(),day=localDay();db[day]=(db[day]||[]).filter(x=>x.id!==id);localStorage.setItem(NUTRITION_KEY,JSON.stringify(db));renderNutrition()}
$('#foodForm').addEventListener('submit',e=>{e.preventDefault();if(addFood()){e.currentTarget.reset();$('#foodGrams').value=100;$('#foodMeal').value='Desayuno'}});

$('#foodSearch').addEventListener('input',renderFoodSearch);
$('#showFavorites').addEventListener('click',()=>{favoriteOnly=!favoriteOnly;$('#showFavorites').classList.toggle('selected',favoriteOnly);renderFoodSearch()});
