const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],KEY='fit-profile-v1';
let data;try{data=JSON.parse(localStorage.getItem(KEY)||'null')}catch{data=null}
let settingActivity=data?.activity||1.55,settingGoal=data?.goal||'lose';
function calc(d){const bmr=10*d.weight+6.25*d.height-5*d.age+(d.sex==='male'?5:-161),tdee=bmr*d.activity,mult=d.goal==='lose'?.82:d.goal==='gain'?1.1:1,cal=Math.round(tdee*mult),protein=Math.round(d.weight*(d.goal==='lose'?2:1.8)),fat=Math.round(d.weight*.8),carbs=Math.max(0,Math.round((cal-protein*4-fat*9)/4));return{cal,protein,fat,carbs}}
function render(){if(!data)return;const m=calc(data);$('#weight').textContent=data.weight.toFixed(1);$('#fat').textContent=data.fat?data.fat.toFixed(1):'—';$('#calories').textContent=m.cal.toLocaleString('es-PE');$('#protein').innerHTML=m.protein+'<small> g</small>';$('#carbs').innerHTML=m.carbs+'<small> g</small>';$('#fats').innerHTML=m.fat+'<small> g</small>';$('#weightState').textContent=data.goal==='lose'?'Objetivo: pérdida de grasa':data.goal==='gain'?'Objetivo: ganancia muscular':'Objetivo: mantenimiento';$('#setup h2').textContent='Perfil configurado';$('#setup p').textContent='Tus recomendaciones están calculadas con tus datos actuales.';$('#openProfile').innerHTML='Editar <b>→</b>';$('.fatRing').style.background=data.fat?'conic-gradient(var(--lime) 0 '+Math.min(100,data.fat)+'%,#1b2529 '+Math.min(100,data.fat)+'% 100%)':'conic-gradient(#1b2529 0 100%)'}
function preview(){const d={weight:+$('#sWeight').value,height:+$('#sHeight').value,age:+$('#sAge').value,sex:$('#sSex').value,activity:+settingActivity,goal:settingGoal};if(!d.weight||!d.height||!d.age){$('#previewCalories').textContent='— kcal';$('#previewMacros').textContent='Completa tus datos para calcularlo.';return}const m=calc(d);$('#previewCalories').textContent=m.cal.toLocaleString('es-PE')+' kcal';$('#previewMacros').textContent='Proteína '+m.protein+'g · Carbos '+m.carbs+'g · Grasas '+m.fat+'g'}
function syncSettings(){if(data){$('#sWeight').value=data.weight;$('#sFat').value=data.fat||'';$('#sHeight').value=data.height;$('#sAge').value=data.age;$('#sSex').value=data.sex;settingActivity=data.activity;settingGoal=data.goal}$$('#mobility button').forEach(b=>b.classList.toggle('selected',+b.dataset.value===+settingActivity));$$('#goalSwitch button').forEach(b=>b.classList.toggle('selected',b.dataset.goal===settingGoal));preview()}
function go(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id===view));$$('nav [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='settingsView')syncSettings();window.scrollTo({top:0,behavior:'instant'})}
$$('nav [data-view]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.view)));
$('#openProfile').addEventListener('click',()=>go('settingsView'));$('.avatar').addEventListener('click',()=>go('settingsView'));
$$('#mobility button').forEach(b=>b.addEventListener('click',()=>{settingActivity=+b.dataset.value;$$('#mobility button').forEach(x=>x.classList.toggle('selected',x===b));preview()}));
$$('#goalSwitch button').forEach(b=>b.addEventListener('click',()=>{settingGoal=b.dataset.goal;$$('#goalSwitch button').forEach(x=>x.classList.toggle('selected',x===b));preview()}));
['sWeight','sHeight','sAge','sSex','sFat'].forEach(id=>$('#'+id).addEventListener('input',preview));
$('#settingsForm').addEventListener('submit',e=>{e.preventDefault();data={weight:+$('#sWeight').value,fat:+$('#sFat').value||null,height:+$('#sHeight').value,age:+$('#sAge').value,sex:$('#sSex').value,activity:+settingActivity,goal:settingGoal};localStorage.setItem(KEY,JSON.stringify(data));render();go('homeView')});
render();