import{FOODS,EXERCISES,ROUTINES}from'./data.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],KEY='fit-v2',old=JSON.parse(localStorage.getItem('fit-v1')||'null');
let state=JSON.parse(localStorage.getItem(KEY)||'null')||old||{body:[],foods:[],sets:[],plan:null,goals:{}};state.body??=[];state.foods??=[];state.sets??=[];state.goals??={};
const save=()=>localStorage.setItem(KEY,JSON.stringify(state)),today=()=>new Date().toISOString().slice(0,10),last=a=>a[a.length-1],fmt=(n,d=0)=>Number(n||0).toFixed(d);
$('#bodyDate').value=today();FOODS.forEach((x,i)=>$('#food').add(new Option(x.name,i)));EXERCISES.forEach(x=>{['exercise','targetExercise','chartExercise'].forEach(id=>$('#'+id).add(new Option(x.name,x.name)))});
$('#nav').onclick=e=>{if(!e.target.dataset.view)return;$$('#nav button').forEach(x=>x.classList.toggle('active',x===e.target));$$('.view').forEach(x=>x.classList.toggle('active',x.id===e.target.dataset.view));setTimeout(drawAll,30)};
$('#bodyForm').onsubmit=e=>{e.preventDefault();const x={date:$('#bodyDate').value,weight:+$('#weight').value,fat:+$('#fat').value||null,waist:+$('#waist').value||null,neck:+$('#neck').value||null,hips:+$('#hips').value||null};state.body=state.body.filter(v=>v.date!==x.date);state.body.push(x);state.body.sort((a,b)=>a.date.localeCompare(b.date));save();render()};
$('#planForm').onsubmit=e=>{e.preventDefault();const b=last(state.body);if(!b)return alert('Registra primero tu peso');const age=+$('#age').value,h=+$('#height').value,a=+$('#activity').value,sex=$('#sex').value,g=$('#goalType').value,rate=+$('#rate').value,bmr=10*b.weight+6.25*h-5*age+(sex==='male'?5:-161),tdee=bmr*a;let delta=g==='maintain'?0:(rate*7700/7)*(g==='lose'?-1:1);delta=g==='lose'?Math.max(delta,-tdee*.25):g==='gain'?Math.min(delta,tdee*.15):0;let cal=Math.round(tdee+delta);cal=Math.max(cal,sex==='male'?1500:1200);const p=Math.round(b.weight*(g==='lose'?2:1.8)),f=Math.round(b.weight*(g==='gain'?1:.8)),c=Math.max(0,Math.round((cal-p*4-f*9)/4));state.plan={bmr:Math.round(bmr),tdee:Math.round(tdee),cal,p,f,c,goal:g,rate};save();render()};
$('#foodForm').onsubmit=e=>{e.preventDefault();const x=FOODS[+$('#food').value],g=+$('#grams').value,k=g/100;state.foods.push({id:Date.now(),date:today(),name:x.name,grams:g,kcal:x.kcal*k,p:x.p*k,c:x.c*k,f:x.f*k});save();render()};
$('#workoutForm').onsubmit=e=>{e.preventDefault();const n=+$('#setCount').value,base=Date.now();for(let i=0;i<n;i++)state.sets.push({id:base+i,date:today(),exercise:$('#exercise').value,load:+$('#load').value,reps:+$('#reps').value,rir:+$('#rir').value,session:base});save();render()};
$('#goalForm').onsubmit=e=>{e.preventDefault();state.goals={weight:+$('#targetWeight').value||null,fat:+$('#targetFat').value||null,exercise:$('#targetExercise').value,target1rm:+$('#target1rm').value||null};save();render()};
$('#exercise').onchange=render;$('#chartExercise').onchange=drawAll;
$('#exportBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='fit-backup-'+today()+'.json';a.click()};
const e1rm=s=>s.load*(1+s.reps/30),meals=()=>state.foods.filter(x=>x.date===today()),sum=k=>meals().reduce((a,x)=>a+x[k],0);
function mealSuggestions(p){if(!p)return'<p>Calcula tu plan para recibir sugerencias.</p>';const rp=Math.max(0,p.p-sum('p')),rc=Math.max(0,p.c-sum('c')),rf=Math.max(0,p.f-sum('f')),rk=Math.max(0,p.cal-sum('kcal'));let out=[];if(rp>25)out.push('Proteína: 150–200 g de pollo, pavo, atún o pescado puede ayudarte a cerrar el día.');if(rc>40)out.push('Carbohidratos: arroz, papa, camote, avena o quinua según las calorías restantes.');if(rf>15)out.push('Grasas: palta, maní o una pequeña porción de aceite de oliva.');if(rk<150)out.push('Estás cerca del objetivo calórico; prioriza alimentos de baja densidad energética si aún tienes hambre.');return out.map(x=>'<div class="pill">'+x+'</div>').join('')||'<div class="pill good">Tus macros están cerca del objetivo.</div>'}
function render(){const b=last(state.body),first=state.body[0],p=state.plan;$('#dWeight').textContent=b?.weight??'—';$('#dFat').textContent=b?.fat??'—';$('#dCalories').textContent=p?.cal??'—';$('#dProtein').textContent=p?.p??'—';$('#tdee').textContent=p?.tdee??'—';$('#calTarget').textContent=p?.cal??'—';$('#proteinTarget').textContent=p?p.p+' g':'—';$('#macroTarget').textContent=p?p.c+' / '+p.f+' g':'—';
$('#fatMass').textContent=b?.fat?fmt(b.weight*b.fat/100,1)+' kg':'—';$('#leanMass').textContent=b?.fat?fmt(b.weight*(1-b.fat/100),1)+' kg':'—';$('#weightChange').textContent=b&&first?((b.weight-first.weight)>0?'+':'')+fmt(b.weight-first.weight,1)+' kg':'—';$('#waistChange').textContent=b?.waist&&first?.waist?fmt(b.waist-first.waist,1)+' cm':'—';
$('#bodyHistory').innerHTML=[...state.body].reverse().slice(0,20).map(x=>'<div class="row"><span><b>'+x.date+'</b></span><span>'+x.weight+' kg'+(x.fat?' · '+x.fat+'% grasa':'')+(x.waist?' · '+x.waist+' cm cintura':'')+'</span></div>').join('')||'<p>Sin mediciones.</p>';
$('#foodSummary').innerHTML='<p><b>'+Math.round(sum('kcal'))+(p?' / '+p.cal:'')+' kcal</b> · P '+Math.round(sum('p'))+(p?'/'+p.p:'')+' · C '+Math.round(sum('c'))+(p?'/'+p.c:'')+' · G '+Math.round(sum('f'))+(p?'/'+p.f:'')+'</p>';$('#foodLog').innerHTML=[...meals()].reverse().map(x=>'<div class="row"><span>'+x.name+' · '+x.grams+' g</span><span>'+Math.round(x.kcal)+' kcal · '+Math.round(x.p)+'P</span></div>').join('');$('#mealAdvice').innerHTML=mealSuggestions(p);
const recent=[...state.sets].reverse().slice(0,20);$('#workoutLog').innerHTML=recent.map(x=>'<div class="row"><span><b>'+x.exercise+'</b> · '+x.load+'×'+x.reps+' · RIR '+x.rir+'</span><span>1RM '+fmt(e1rm(x),1)+' kg</span></div>').join('')||'<p>Sin entrenamiento.</p>';
const ex=$('#exercise').value,es=state.sets.filter(x=>x.exercise===ex),s=last(es);$('#strengthAdvice').innerHTML=s?'<p>Última referencia: <b>'+s.load+' kg × '+s.reps+'</b>, RIR '+s.rir+'. '+(s.rir>=3?'Puedes intentar +2.5 kg manteniendo el rango de repeticiones.':s.rir>=1?'Intenta sumar 1 repetición antes de subir carga.':'Repite o reduce ligeramente hasta recuperar margen técnico.')+'</p>':'<p>Registra el ejercicio para generar progresión.</p>';
const best={};state.sets.forEach(x=>best[x.exercise]=Math.max(best[x.exercise]||0,e1rm(x)));$('#prList').innerHTML=Object.entries(best).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([n,v])=>'<div class="row"><span>'+n+'</span><b>'+fmt(v,1)+' kg</b></div>').join('')||'<p>Aún no hay PRs.</p>';
let adv=[];if(!b)adv.push('Registra tu peso corporal.');if(!p)adv.push('Calcula tu objetivo nutricional.');if(p&&p.p-sum('p')>15)adv.push('Te faltan ~'+Math.round(p.p-sum('p'))+' g de proteína hoy.');if(!state.sets.some(x=>x.date===today()))adv.push('Todavía no registraste entrenamiento hoy.');$('#todayAdvice').innerHTML=adv.map(x=>'<div class="pill">'+x+'</div>').join('')||'<div class="pill good">Registros principales al día.</div>';
let progress=0,proj='';if(b&&state.goals.weight){const total=Math.abs((first?.weight??b.weight)-state.goals.weight),done=Math.abs((first?.weight??b.weight)-b.weight);progress=total?Math.min(100,Math.max(0,done/total*100)):100;if(state.body.length>=2){const old=state.body[Math.max(0,state.body.length-5)],days=Math.max(1,(new Date(b.date)-new Date(old.date))/86400000),weekly=(b.weight-old.weight)/days*7,remain=state.goals.weight-b.weight;if(weekly&&remain/weekly>0)proj='Tendencia reciente: '+fmt(weekly,2)+' kg/sem · aproximadamente '+Math.ceil(remain/weekly)+' semanas al objetivo.'}}$('#progressScore').textContent=Math.round(progress)+'%';$('#projection').textContent=proj||'Registra datos con regularidad para obtener una proyección.';$('#status').textContent=b?'Peso '+b.weight+' kg'+(b.fat?' · '+b.fat+'% grasa':''):'Empieza registrando tus datos';
let cards=[];if(state.goals.weight)cards.push('<article class="card"><h3>Peso</h3><b>'+b?.weight+' → '+state.goals.weight+' kg</b><p>'+Math.round(progress)+'% estimado</p></article>');if(state.goals.fat)cards.push('<article class="card"><h3>Grasa corporal</h3><b>'+(b?.fat??'—')+' → '+state.goals.fat+'%</b></article>');if(state.goals.target1rm){const v=best[state.goals.exercise]||0;cards.push('<article class="card"><h3>'+state.goals.exercise+'</h3><b>'+fmt(v,1)+' → '+state.goals.target1rm+' kg</b><p>'+Math.min(100,Math.round(v/state.goals.target1rm*100))+'% del objetivo</p></article>')}$('#goalCards').innerHTML=cards.join('')||'<article class="card"><p>Crea tu primer objetivo.</p></article>';
$('#routineList').innerHTML=ROUTINES.map(r=>'<article class="card"><h3>'+r.name+'</h3>'+r.days.map((d,i)=>'<div class="routineDay"><b>Día '+(i+1)+'</b><span>'+d.join(' · ')+'</span></div>').join('')+'</article>').join('');
if(state.goals.weight)$('#targetWeight').value=state.goals.weight;if(state.goals.fat)$('#targetFat').value=state.goals.fat;if(state.goals.exercise)$('#targetExercise').value=state.goals.exercise;if(state.goals.target1rm)$('#target1rm').value=state.goals.target1rm;setTimeout(drawAll,20)}
function chart(id,values){const c=$(id);if(!c||c.offsetParent===null)return;const r=c.getBoundingClientRect(),d=devicePixelRatio||1,ctx=c.getContext('2d');c.width=r.width*d;c.height=r.height*d;ctx.scale(d,d);ctx.clearRect(0,0,r.width,r.height);if(values.length<2){ctx.fillStyle='#93a0af';ctx.font='13px system-ui';ctx.fillText('Necesitas más registros',12,30);return}const min=Math.min(...values),max=Math.max(...values),pad=18,range=max-min||1;ctx.strokeStyle='#273342';for(let i=0;i<4;i++){const y=pad+(r.height-pad*2)*i/3;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(r.width-pad,y);ctx.stroke()}ctx.strokeStyle='#72e5b1';ctx.lineWidth=3;ctx.beginPath();values.forEach((v,i)=>{const x=pad+(r.width-pad*2)*i/(values.length-1),y=pad+(max-v)/range*(r.height-pad*2);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
function drawAll(){chart('#miniChart',state.body.slice(-10).map(x=>x.weight));chart('#weightChart',state.body.map(x=>x.weight));chart('#fatChart',state.body.filter(x=>x.fat).map(x=>x.fat));const ex=$('#chartExercise').value;chart('#strengthChart',state.sets.filter(x=>x.exercise===ex).map(e1rm));const sessions={};state.sets.forEach(x=>sessions[x.session||x.date]=(sessions[x.session||x.date]||0)+x.load*x.reps);chart('#volumeChart',Object.values(sessions).slice(-12))}
addEventListener('resize',()=>setTimeout(drawAll,80));render();