export const FOODS=[
{name:"Pechuga de pollo",kcal:165,p:31,c:0,f:3.6},{name:"Arroz cocido",kcal:130,p:2.7,c:28,f:.3},{name:"Huevo",kcal:143,p:12.6,c:.7,f:9.5},{name:"Avena",kcal:389,p:16.9,c:66.3,f:6.9},{name:"Papa sancochada",kcal:87,p:1.9,c:20.1,f:.1},{name:"Atún al agua",kcal:116,p:25.5,c:0,f:.8},{name:"Palta",kcal:160,p:2,c:8.5,f:14.7},{name:"Plátano",kcal:89,p:1.1,c:22.8,f:.3},{name:"Leche entera",kcal:61,p:3.2,c:4.8,f:3.3},{name:"Yogur griego natural",kcal:97,p:9,c:3.9,f:5},{name:"Carne de res magra cocida",kcal:217,p:26,c:0,f:12},{name:"Pavo cocido",kcal:135,p:29,c:0,f:1},{name:"Salmón cocido",kcal:206,p:22,c:0,f:12},{name:"Tilapia cocida",kcal:128,p:26,c:0,f:2.7},{name:"Lentejas cocidas",kcal:116,p:9,c:20,f:.4},{name:"Frejoles cocidos",kcal:127,p:8.7,c:22.8,f:.5},{name:"Quinua cocida",kcal:120,p:4.4,c:21.3,f:1.9},{name:"Camote cocido",kcal:90,p:2,c:20.7,f:.2},{name:"Pasta cocida",kcal:157,p:5.8,c:30.9,f:.9},{name:"Pan integral",kcal:247,p:13,c:41,f:4.2},{name:"Queso fresco",kcal:264,p:18,c:4,f:20},{name:"Claras de huevo",kcal:52,p:10.9,c:.7,f:.2},{name:"Manzana",kcal:52,p:.3,c:13.8,f:.2},{name:"Naranja",kcal:47,p:.9,c:11.8,f:.1},{name:"Fresa",kcal:32,p:.7,c:7.7,f:.3},{name:"Papaya",kcal:43,p:.5,c:10.8,f:.3},{name:"Brócoli cocido",kcal:35,p:2.4,c:7.2,f:.4},{name:"Espinaca",kcal:23,p:2.9,c:3.6,f:.4},{name:"Tomate",kcal:18,p:.9,c:3.9,f:.2},{name:"Aceite de oliva",kcal:884,p:0,c:0,f:100},{name:"Maní",kcal:567,p:25.8,c:16.1,f:49.2}
];
export const EXERCISES=[
{id:"bench",name:"Press banca",muscle:"Pecho",equipment:"Barra"},{id:"incline",name:"Press inclinado",muscle:"Pecho",equipment:"Barra/Mancuernas"},{id:"pushup",name:"Flexiones",muscle:"Pecho",equipment:"Peso corporal"},{id:"squat",name:"Sentadilla",muscle:"Cuádriceps",equipment:"Barra"},{id:"legpress",name:"Prensa",muscle:"Cuádriceps",equipment:"Máquina"},{id:"lunge",name:"Zancadas",muscle:"Piernas",equipment:"Mancuernas"},{id:"deadlift",name:"Peso muerto",muscle:"Cadena posterior",equipment:"Barra"},{id:"rdl",name:"Peso muerto rumano",muscle:"Femoral",equipment:"Barra/Mancuernas"},{id:"hipthrust",name:"Hip thrust",muscle:"Glúteos",equipment:"Barra"},{id:"ohp",name:"Press militar",muscle:"Hombros",equipment:"Barra"},{id:"lateral",name:"Elevaciones laterales",muscle:"Hombros",equipment:"Mancuernas"},{id:"row",name:"Remo con barra",muscle:"Espalda",equipment:"Barra"},{id:"pulldown",name:"Jalón al pecho",muscle:"Espalda",equipment:"Polea"},{id:"pullup",name:"Dominadas",muscle:"Espalda",equipment:"Peso corporal"},{id:"curl",name:"Curl bíceps",muscle:"Bíceps",equipment:"Mancuernas"},{id:"triceps",name:"Extensión tríceps",muscle:"Tríceps",equipment:"Polea"},{id:"calf",name:"Elevación de gemelos",muscle:"Pantorrilla",equipment:"Máquina"},{id:"plank",name:"Plancha",muscle:"Core",equipment:"Peso corporal"}
];
export const ROUTINES=[
{name:"Full Body 3 días",days:[["Sentadilla","Press banca","Jalón al pecho","Peso muerto rumano","Elevaciones laterales"],["Prensa","Press militar","Remo con barra","Hip thrust","Curl bíceps"],["Peso muerto","Press inclinado","Dominadas","Zancadas","Extensión tríceps"]]},
{name:"Upper / Lower 4 días",days:[["Press banca","Remo con barra","Press militar","Jalón al pecho","Curl bíceps","Extensión tríceps"],["Sentadilla","Peso muerto rumano","Prensa","Elevación de gemelos"],["Press inclinado","Dominadas","Elevaciones laterales","Remo con barra","Curl bíceps"],["Peso muerto","Zancadas","Hip thrust","Prensa","Elevación de gemelos"]]},
{name:"Push Pull Legs 6 días",days:[["Press banca","Press inclinado","Press militar","Elevaciones laterales","Extensión tríceps"],["Peso muerto","Dominadas","Remo con barra","Jalón al pecho","Curl bíceps"],["Sentadilla","Prensa","Peso muerto rumano","Elevación de gemelos"],["Press banca","Press inclinado","Press militar","Elevaciones laterales","Extensión tríceps"],["Dominadas","Remo con barra","Jalón al pecho","Curl bíceps"],["Sentadilla","Zancadas","Hip thrust","Prensa","Elevación de gemelos"]]}
];